--- # PROD Bookmaking App PREP ansible script
- hosts: repo
  remote_user: ck
  connection: ssh
  gather_facts: no
  tasks:
  - name: Bookmaking App {{ version }} prep 
    pause: prompt="Double Check your script!!..Hit Return to continue or Ctrl-C to abort"

#  - name: Wait for the remote node
#    local_action: wait_for_host host=repo port=22 state=started delay=10
 
  - name: Creating a compressed archive of the Bookmaking App
#    archive:
#      path: /home/ck/MACH45/PROD/{{ version }}
#      dest: /home/ck/MACH45/PROD/{{ version }}.tgz
    shell: cd /home/ck/MACH45/PROD && tar -cvpzf {{ version }}.tar.gz {{ version }}/

  - name: Fetching file {{ version }}.tar.gz from repo
    fetch: src=/home/ck/MACH45/PROD/{{ version }}.tar.gz dest=/tmp flat=yes


- hosts: localhost
  remote_user: james.tandi
#  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Bookmaking App {{ version }} Deployment Prep
    unarchive: src=/tmp/{{ version }}.tar.gz dest=~/Documents/BookAppRelease/PROD

  - name: Assigning execute permission to StartDashboardClient.sh
    file: path=~/Documents/BookAppRelease/PROD/{{ version }}/StartDashboardClient.sh mode=0775


  - name: StartDashboardClient.sh to StartDashboardClient
    command: mv ~/Documents/BookAppRelease/PROD/{{ version }}/StartDashboardClient.sh ~/Documents/BookAppRelease/PROD/{{ version }}/StartDashboardClient

  - name: Compressing Bookmaking App {{ version }} to be ready for deployment
    shell: cd ~/Documents/BookAppRelease/PROD && tar -cvpzf {{ version }}.tar.gz {{ version }}/
