---
- hosts: '{{ ip }}'
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Get running processes
#    shell: ps aux | grep -F 'chromium' | grep -v -F 'grep' | awk '{ print $2 }'
    shell: ps aux | grep -e 'chromium\|chrome' | grep -v -F 'grep' | awk '{ print $2 }'
    register: running_processes

  - name: Kill running processes
    shell: "kill {{ item }}"
    with_items: "{{ running_processes.stdout_lines }}"
    ignore_errors: yes

  - wait_for:
      path: "/proc/{{ item }}/status"
      state: absent
    with_items: "{{ running_processes.stdout_lines }}"
    ignore_errors: yes
    register: killed_processes

  - name: Force kill stuck processes
    shell: "kill -9 {{ item }}"
    with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"


  - name: Only run "update_cache=yes" if the last one is more than 86400 (1day) seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 86400
 
  - name: Install the latest Google Chrome version
    apt:
      name: google-chrome-stable 
      state: latest

  - name: Install the latest Chromium Browser version
    apt:
      name: chromium-browser
      state: latest
    register: chromiumlatest

  - name: chromium updated - configuring proxy settings
    replace: dest=/usr/share/applications/chromium-browser.desktop regexp='^Exec=chromium-browser %U$' replace='Exec=chromium-browser %U --proxy-server="http://52.196.102.91:8080" --disable-extensions --disable-gpu'
#    when: chromiumlatest|changed
    tags: a1

  - name: chromium updated - configuring proxy settings
    replace: dest=/usr/share/applications/chromium-browser.desktop regexp='^Exec=chromium-browser$' replace='Exec=chromium-browser --proxy-server="http://52.196.102.91:8080" --disable-extensions --disable-gpu'
#    when: chromiumlatest|changed
    tags: a2

  - name: Confirming if the latest Browsers version have been installed
    shell: dpkg -l | grep -e 'google-chrome-stable\|chromium-browser' | awk '{print $3}'
    register: browsers
  - debug: var=browsers.stdout_lines
    tags: a3
  
  - name: Confirming if the Chromium proxy settings are correct
    shell: cat /usr/share/applications/chromium-browser.desktop | grep proxy
    register: proxy
  - debug: var=proxy.stdout_lines
    tags: a4
