---
- hosts: '{{ ip }}'
  become: yes
  become_method: sudo
  gather_facts: no
#  ignore_errors: yes

  tasks:

  - name: Removing Kernel 4.4.0-116
    apt: name={{item}} state=absent
    with_items:
      - linux-headers-4.4.0-116
      - linux-headers-4.4.0-116-generic
      - linux-image-4.4.0-116-generic
      - linux-image-extra-4.4.0-116-generic

  - name:  Rebooting the system for the updates to take effect
    command: shutdown -r now
