---
- hosts: '{{ ip }}'
  become: yes
  become_method: sudo
  gather_facts: no
#  ignore_errors: yes


  tasks:
  - name: Copying Chrome proxyConfig file from src to dest
    copy:
      src: /tmp/proxyConfig
      dest: /etc/opt/chrome/policies/managed/proxyConfig
      owner: root
      group: root
      mode: 0644

  - name: Confirming if the chrome policy list has been added
    shell: ls /etc/opt/chrome/policies/managed/ | grep proxy*
    register: proxy
  - debug: var=proxy.stdout_lines
